### ISSUE TITLE
有沒有更詳細的安裝步驟？看了解釋還是不太懂怎麼安裝

### ISSUE THREAD

**Issue by laubonghaudoi** [zhangkaiser/zhime#1]
支持作者，終於有ChromeOS rime了。

**Comment by zhangkaiser** [comment]
後續會更新/簡化安裝步驟。

安装步骤:

- 先確定已经安装上`zhime`和`librime`兩個Chrome擴展應用。
- 此時，可以先将`librime`的擴展ID复制到`zhime`擴展的配置選項頁(活动页)中并點擊`保存`
- 然後在`librime`配置選項頁中選擇部署/配置所需要的解析方案（部署並點擊`確定`完成後，必須點擊底部的`同步此次修改`按鈕）。
- `同步`完成後就可以去`os設置>語言與輸入法>輸入法`的选项中添加並找到`ZHIME`选项(應該就可以使用rime输入法了)。

當前，部署方式支持`內置方案`，`原始文件構建`，`已構建文件上傳`。

`原始文件構建`，可包含`詞庫`(dict.yaml)和`方案配置`(custom.yaml)文件和`default.yaml`等初始化構建需要的文件，需要一次選擇多個構建所依賴的文件。
`已構建文件上傳`可以選擇文件夾（例`build`文件夾，包含構建後的方案配置文件，詞庫需要的二進制文件）。
