### ISSUE TITLE
非常感谢您的项目，如果在说明里多一些图文结合的配置过程就好了

### ISSUE THREAD

**Issue by fish1968** [zhangkaiser/zhime#2]
我摸索了一小会儿，最开始很奇怪，打字下面的选词框是空白的，配置的也不太明白，最好不知道怎么的，突然就能玩起来了。
非常感谢您的项目，解决了我使用 chromebook 的一大痛点。

**Comment by zhangkaiser** [comment]
感谢您的反馈，后续有时间会添加一些内容说明和交互上的简化调整。
